// Code generated by protoc-gen-gogo.
// source: github.com/asyou-me/protorpc/types/api.proto
// DO NOT EDIT!

/*
	Package types is a generated protocol buffer package.

	It is generated from these files:
		github.com/asyou-me/protorpc/types/api.proto

	It has these top-level messages:
		RequestHeader
		ResponseHeader
		Test
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Const int32

const (
	Const_ZERO                   Const = 0
	Const_MAX_REQUEST_HEADER_LEN Const = 1024
)

var Const_name = map[int32]string{
	0:    "ZERO",
	1024: "MAX_REQUEST_HEADER_LEN",
}
var Const_value = map[string]int32{
	"ZERO": 0,
	"MAX_REQUEST_HEADER_LEN": 1024,
}

func (x Const) String() string {
	return proto.EnumName(Const_name, int32(x))
}
func (Const) EnumDescriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

// 请求头
type RequestHeader struct {
	Id                         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method                     string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	RawRequestLen              uint32 `protobuf:"varint,3,opt,name=raw_request_len,json=rawRequestLen,proto3" json:"raw_request_len,omitempty"`
	SnappyCompressedRequestLen uint32 `protobuf:"varint,4,opt,name=snappy_compressed_request_len,json=snappyCompressedRequestLen,proto3" json:"snappy_compressed_request_len,omitempty"`
	Checksum                   uint32 `protobuf:"varint,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Token                      string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

// 结果头
type ResponseHeader struct {
	Id                          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RawResponseLen              uint32 `protobuf:"varint,3,opt,name=raw_response_len,json=rawResponseLen,proto3" json:"raw_response_len,omitempty"`
	SnappyCompressedResponseLen uint32 `protobuf:"varint,4,opt,name=snappy_compressed_response_len,json=snappyCompressedResponseLen,proto3" json:"snappy_compressed_response_len,omitempty"`
	Checksum                    uint32 `protobuf:"varint,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{1} }

// 测试类型
type Test struct {
	A int64 `protobuf:"varint,1,opt,name=A,json=a,proto3" json:"A,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=B,json=b,proto3" json:"B,omitempty"`
	C int64 `protobuf:"varint,3,opt,name=C,json=c,proto3" json:"C,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{2} }

func init() {
	proto.RegisterType((*RequestHeader)(nil), "types.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "types.ResponseHeader")
	proto.RegisterType((*Test)(nil), "types.Test")
	proto.RegisterEnum("types.Const", Const_name, Const_value)
}
func (m *RequestHeader) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *RequestHeader) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintApi(data, i, uint64(m.Id))
	}
	if len(m.Method) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintApi(data, i, uint64(len(m.Method)))
		i += copy(data[i:], m.Method)
	}
	if m.RawRequestLen != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintApi(data, i, uint64(m.RawRequestLen))
	}
	if m.SnappyCompressedRequestLen != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintApi(data, i, uint64(m.SnappyCompressedRequestLen))
	}
	if m.Checksum != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintApi(data, i, uint64(m.Checksum))
	}
	if len(m.Token) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintApi(data, i, uint64(len(m.Token)))
		i += copy(data[i:], m.Token)
	}
	return i, nil
}

func (m *ResponseHeader) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ResponseHeader) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintApi(data, i, uint64(m.Id))
	}
	if len(m.Error) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintApi(data, i, uint64(len(m.Error)))
		i += copy(data[i:], m.Error)
	}
	if m.RawResponseLen != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintApi(data, i, uint64(m.RawResponseLen))
	}
	if m.SnappyCompressedResponseLen != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintApi(data, i, uint64(m.SnappyCompressedResponseLen))
	}
	if m.Checksum != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintApi(data, i, uint64(m.Checksum))
	}
	return i, nil
}

func (m *Test) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Test) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.A != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintApi(data, i, uint64(m.A))
	}
	if m.B != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintApi(data, i, uint64(m.B))
	}
	if m.C != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintApi(data, i, uint64(m.C))
	}
	return i, nil
}

func encodeFixed64Api(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Api(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintApi(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *RequestHeader) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovApi(uint64(m.Id))
	}
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.RawRequestLen != 0 {
		n += 1 + sovApi(uint64(m.RawRequestLen))
	}
	if m.SnappyCompressedRequestLen != 0 {
		n += 1 + sovApi(uint64(m.SnappyCompressedRequestLen))
	}
	if m.Checksum != 0 {
		n += 1 + sovApi(uint64(m.Checksum))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	return n
}

func (m *ResponseHeader) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovApi(uint64(m.Id))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.RawResponseLen != 0 {
		n += 1 + sovApi(uint64(m.RawResponseLen))
	}
	if m.SnappyCompressedResponseLen != 0 {
		n += 1 + sovApi(uint64(m.SnappyCompressedResponseLen))
	}
	if m.Checksum != 0 {
		n += 1 + sovApi(uint64(m.Checksum))
	}
	return n
}

func (m *Test) Size() (n int) {
	var l int
	_ = l
	if m.A != 0 {
		n += 1 + sovApi(uint64(m.A))
	}
	if m.B != 0 {
		n += 1 + sovApi(uint64(m.B))
	}
	if m.C != 0 {
		n += 1 + sovApi(uint64(m.C))
	}
	return n
}

func sovApi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RequestHeader) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Id |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawRequestLen", wireType)
			}
			m.RawRequestLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.RawRequestLen |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnappyCompressedRequestLen", wireType)
			}
			m.SnappyCompressedRequestLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SnappyCompressedRequestLen |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			m.Checksum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Checksum |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseHeader) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Id |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawResponseLen", wireType)
			}
			m.RawResponseLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.RawResponseLen |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnappyCompressedResponseLen", wireType)
			}
			m.SnappyCompressedResponseLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SnappyCompressedResponseLen |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			m.Checksum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Checksum |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Test) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Test: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Test: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field A", wireType)
			}
			m.A = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.A |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			m.B = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.B |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field C", wireType)
			}
			m.C = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.C |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApi(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorApi = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x6a, 0xdb, 0x40,
	0x14, 0x85, 0x2d, 0x5b, 0x32, 0xee, 0xa5, 0x76, 0xc5, 0x50, 0x8c, 0xb0, 0xa9, 0x29, 0x5e, 0x14,
	0x53, 0x6a, 0xab, 0xd0, 0x27, 0x90, 0x55, 0x81, 0x17, 0x6e, 0x4b, 0xa7, 0x2e, 0x94, 0x6e, 0x84,
	0x7e, 0x26, 0xb6, 0x71, 0xa4, 0x99, 0xcc, 0x48, 0x04, 0xef, 0xf2, 0x18, 0x79, 0x9d, 0xec, 0xb2,
	0xcc, 0x22, 0x0f, 0x10, 0x92, 0x17, 0xc9, 0x78, 0xc6, 0x38, 0x0a, 0xf9, 0x59, 0x0c, 0xdc, 0xef,
	0x72, 0xcf, 0xe1, 0x1c, 0x21, 0xf8, 0xb2, 0x5c, 0x17, 0xab, 0x32, 0x9e, 0x24, 0x34, 0x73, 0x23,
	0xb1, 0xa5, 0xe5, 0x38, 0x23, 0x2e, 0xe3, 0xb4, 0xa0, 0x9c, 0x25, 0x6e, 0xb1, 0x65, 0x44, 0xb8,
	0x11, 0x5b, 0x4f, 0xd4, 0x0a, 0x59, 0x6a, 0xd1, 0x1b, 0x57, 0x44, 0x4b, 0xba, 0xa4, 0x5a, 0x10,
	0x97, 0x47, 0x8a, 0x14, 0xa8, 0x49, 0xab, 0x86, 0xd7, 0x06, 0xb4, 0x31, 0x39, 0x29, 0x89, 0x28,
	0x66, 0x24, 0x4a, 0x09, 0x47, 0x1d, 0xa8, 0xaf, 0x53, 0xc7, 0xf8, 0x68, 0x8c, 0x4c, 0x2c, 0x27,
	0xd4, 0x85, 0x66, 0x46, 0x8a, 0x15, 0x4d, 0x9d, 0xba, 0xdc, 0xbd, 0xc1, 0x7b, 0x42, 0x9f, 0xe0,
	0x1d, 0x8f, 0x4e, 0x43, 0xae, 0xc5, 0xe1, 0x31, 0xc9, 0x9d, 0x86, 0x3c, 0x68, 0xe3, 0xb6, 0x5c,
	0xef, 0x2d, 0xe7, 0x24, 0x47, 0x1e, 0x7c, 0x10, 0x79, 0xc4, 0xd8, 0x36, 0x94, 0x91, 0x18, 0x27,
	0x42, 0x90, 0xf4, 0x91, 0xca, 0x54, 0xaa, 0x9e, 0x3e, 0xf2, 0x0f, 0x37, 0x15, 0x8b, 0x1e, 0xb4,
	0x92, 0x15, 0x49, 0x36, 0xa2, 0xcc, 0x1c, 0x4b, 0x5d, 0x1f, 0x18, 0xbd, 0x07, 0xab, 0xa0, 0x1b,
	0x69, 0xd3, 0x54, 0xe9, 0x34, 0x0c, 0x2f, 0x0c, 0xe8, 0x60, 0x22, 0x18, 0xcd, 0x05, 0x79, 0xa1,
	0x97, 0x14, 0x12, 0xce, 0x29, 0xdf, 0xd7, 0xd2, 0x80, 0x46, 0x60, 0xeb, 0x56, 0x5a, 0x5b, 0xa9,
	0xd5, 0x51, 0xb5, 0xf4, 0x7a, 0x17, 0xca, 0x87, 0xc1, 0x73, 0xbd, 0x2a, 0x3a, 0x5d, 0xac, 0xff,
	0xb4, 0xd8, 0x83, 0xc9, 0x2b, 0xcd, 0x86, 0x5f, 0xc1, 0x5c, 0xc8, 0x0f, 0x80, 0xde, 0x82, 0xe1,
	0xa9, 0xdc, 0x0d, 0x6c, 0x44, 0x3b, 0x9a, 0xaa, 0xc8, 0x92, 0xe2, 0x1d, 0xf9, 0x2a, 0x9f, 0xa4,
	0xe4, 0xf3, 0x04, 0x2c, 0x5f, 0x3a, 0x17, 0xa8, 0x05, 0xe6, 0xff, 0x00, 0xff, 0xb2, 0x6b, 0xa8,
	0x0f, 0xdd, 0x1f, 0xde, 0xbf, 0x10, 0x07, 0xbf, 0xff, 0x06, 0x7f, 0x16, 0xe1, 0x2c, 0xf0, 0xbe,
	0x07, 0x38, 0x9c, 0x07, 0x3f, 0xed, 0xb3, 0xd6, 0xd4, 0xbe, 0xbc, 0x1d, 0x18, 0x57, 0xf2, 0xdd,
	0xc8, 0x77, 0x7e, 0x37, 0xa8, 0xc5, 0x4d, 0xf5, 0x57, 0x7c, 0xbb, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0x05, 0xa7, 0x7f, 0x7b, 0x02, 0x00, 0x00,
}
